config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  get 'auth/new' => 'auth#new', as: :new_auth
  post 'auth/create' => 'auth#create', as: :create_auth
  delete 'auth/destroy' => 'auth#destroy', as: :destroy_auth
  get 'dashboard/reload_pick_teams' => 'dashboard#reload_pick_teams'
  post 'dashboard/pick_teams' => 'dashboard#pick_teams'
  post 'user_shares/create_bid' => 'user_shares#create_bid'
  post 'ask/update_js' => 'ask#update_js'

  resources :users
  resources :user_shares
  resources :ask
  resources :bid

end

app/models/user_share.rb
class UserShare < ActiveRecord::Base

  belongs_to :team
  belongs_to :user
  has_many :bids, dependent: :destroy
  has_many :asks, dependent: :destroy

  validates :team_id, presence: true
  validates :user_id, presence: true
  validates :number_of_shares, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validate :has_enough_points

  def has_enough_points
    points = User.find(user_id).points_to_spend
    points_cost = (number_of_shares || 0)  * Team.find(team_id).points_per_share
    if points < points_cost
      errors.add(:points_cost, "is too high. Sorry, you currently don't have enough points.")
    end
  end
end

app/controllers/user_shares_controller.rb
class UserSharesController < ApplicationController

  before_action :current_user

  def new
    @user_share = UserShare.new
    @user_shares = current_user.user_shares
  end

  def create
    @user_share = UserShare.where(user_id: current_user.id, team_id: user_shares_params[:team_id])[0]
    if @user_share.present?
      is_saved_or_update = @user_share.update!(number_of_shares: @user_share[:number_of_shares] + user_shares_params[:number_of_shares].to_i)
    else
      @user_share = UserShare.new(user_shares_params.merge(user_id: current_user.id))
      is_saved_or_update = @user_share.save
    end
    if is_saved_or_update
      params[:ask_points_share] == "" ? intial_ask_points = @user_share.team.points_per_share*10 : intial_ask_points = @user_share.number_of_shares*params[:ask_points_share].to_i
      Ask.create!(user_share_id: @user_share.id, shares: @user_share.number_of_shares, points: intial_ask_points.round(2))
      points = current_user.points_to_spend
      points_spent = @user_share.number_of_shares * @user_share.team.points_per_share
      current_user.update(points_to_spend: points-points_spent)
      flash[:notice] = "#{@user_share.number_of_shares} shares of #{Team.find(@user_share.team_id).name} successfully purchased!"
      redirect_to new_user_share_path
    else
      errors = @user_share.errors.full_messages.join("  ")
      flash[:notice] = "#{errors}"
      redirect_to new_user_share_path
    end
  end

  def edit
    @asks = UserShare.find(params[:id]).asks
    @bids = UserShare.find(params[:id]).bids
  end

  def destroy
    @user_share = UserShare.find(params[:id])
    if @user_share.delete
      points = current_user.points_to_spend
      points_return = @user_share.number_of_shares * @user_share.team.points_per_share
      current_user.update(points_to_spend: points + points_return)
      flash[:notice] = "#{@user_share.number_of_shares} shares of #{Team.find(@user_share.team_id).name} successfully removed!"
      redirect_to new_user_share_path
    end
  end

  def create_bid
    team = Team.find_by_name(params[:team_name])
    @user_share = current_user.user_shares.where(team_id: team.id).first
    if @user_share && @user_share != []
      @bid = Bid.create!(user_share_id: @user_share.id, shares: bid_params[:bid_shares], points: bid_params[:bid_points_share])
    else
      @user_share = UserShare.create!(user_id: current_user.id, team_id: team.id, number_of_shares: 0)
      @bid = Bid.create!(user_share_id: @user_share.id, shares: bid_params[:bid_shares], points: bid_params[:bid_points_share])
    end
    respond_to do |format|
    format.json { render json: {team: team, bid: @bid }}
    end

  end

  # def create_ask
  #   team = Team.find(params[:id])
  #   user_share = team.user_shares.where(user_id: current_user.id).first
  #   @ask = user_share.asks.where(points: points)
  #   @user_share = @ask.user_share
  #   same_as_other_ask = UserShare.find(@user_share.id).asks.where(points: ask_params[:points]).length > 0
  #   if @ask.points != ask_params[:points] && @ask.shares >= ask_params[:shares].to_i && same_as_other_ask
  #     @ask.update(shares: @ask.shares - ask_params[:shares].to_i)
  #     @ask_add_shares = UserShare.find(@user_share.id).asks.where(points: ask_params[:points])[0]
  #     @ask_add_shares.update(shares: @ask_add_shares[:shares] + ask_params[:shares].to_i)
  #     flash[:notice] = "You combined shares!"
  #     redirect_to edit_user_share_path(@ask.user_share)
  #   elsif  @ask.shares != ask_params[:shares].to_i && @ask.points != ask_params[:points] && @ask.shares > ask_params[:shares].to_i
  #     @ask.update(shares: @ask.shares - ask_params[:shares].to_i,)
  #     new_ask = Ask.new(ask_params.merge(user_share_id: @user_share.id))
  #     new_ask.save
  #     flash[:notice] = "You split shares!"
  #     redirect_to edit_user_share_path(@ask.user_share)
  #   elsif @ask.shares == ask_params[:shares].to_i &&  @ask.points != ask_params[:points]
  #     @ask.update(points: ask_params[:points])
  #     flash[:notice] = "You changed ask points!"
  #     redirect_to edit_user_share_path(@ask.user_share)
  #   elsif @ask.shares < bid_params[:shares].to_i
  #     flash[:notice] = "Error - Too Many Shares"
  #     redirect_to edit_user_share_path(@bid.user_share)
  #   end
  # end

  private
  def user_shares_params
    params.require(:user_share).permit(:team_id, :number_of_shares)
  end

  def bid_params
    params.permit(:team_name, :bid_shares, :bid_points_share)
  end

  def ask_params
    params.require(:ask).permit(:team_id, :team_name, :ask_shares, :ask_points_share)
  end

end

app/views/user_shares/edit.html.erb
<% @bids.each do |bid| %>
  <%= form_for bid do |f| %>
    <legend>
      <span>
        <%= "Edit Bid for #{bid.user_share.team.name} Stock:" %>
      </span>
    </legend>
    <div class = "form-group col-md-4">
      <%= f.label :shares, "Number of Shares" %>
      <%= f.text_field :shares, :class=>"form-control", :placeholder=>"Number of Shares" %>
    </div>
    <div class = "form-group col-md-8">
      <%= f.label :points, "Bid Points per Share" %>
      <%= f.number_field :points, :class=>"form-control", :step => 'any' %>
    </div>
    <div class="col-md-4" style="margin-top: 24px margin-bottom: 100px">
      <%= f.button "Create | Edit Bid", :class=> "btn btn-primary"%>
    </div>
  <% end %>
<% end %>


<% @asks.each do |ask| %>
  <%= form_for ask do |f| %>
    <legend>
      <span>
        <%= "Edit Ask for #{ask.user_share.team.name} Stock:" %>
      </span>
      <span class= "pull-right">
        <%= "Total Shares: #{ask.user_share.number_of_shares} " %>
      </span>
    </legend>
    <div class = "form-group col-md-4">
      <%= f.label :shares, "Number of Shares" %>
      <%= f.text_field :shares, :class=>"form-control", :placeholder=>"Number of Shares" %>
    </div>
    <div class = "form-group col-md-8">
      <%= f.label :points, "Ask Points per Share" %>
      <%= f.number_field :points, :class=>"form-control", :step => 'any' %>
    </div>
    <div class="col-md-4" style="margin-top: 24px margin-bottom: 100px">
      <%= f.button "Create | Edit Ask", :class=> "btn btn-primary"%>
    </div>
  <% end %>
<% end %>

app/views/user_shares/new.html.erb
<%= form_for @user_share do |f| %>
  <legend>
    <span>
      Initial Team Stock Buy:
    </span>
    <span class="pull-right">
      <%= "available points #{current_user.points_to_spend.round(2)}" %>
    </span>
  </legend>
  <div class = "form-group col-md-8">
    <%= f.label :team_id, "Team | Cost" %>
    <%= f.collection_select(:team_id, Team.order(:name), :id, :name_with_points, {}, :class=> "form-control") %>
  </div>
  <div class = "form-group col-md-4">
    <%= f.label :number_of_shares, "Number of Shares" %>
    <%= f.text_field :number_of_shares, :class=>"form-control", :placeholder=>"Number of Shares" %>
  </div>
  <div class = "form-group col-md-8">
    <%= label_tag :ask_points_share, "Initial Ask Points per Share" %>
    <%= number_field_tag :ask_points_share, value = nil, :class=>"form-control", :placeholder=>"Default: Initial Points x 10 - set at trade" %>
  </div>
  <div class="col-md-4" style="margin-top: 24px">
    <%= f.button "Create Bid", :class=> "btn btn-primary pull-right"%>
  </div>
<% end %>
<p></p>

<table class = "table" style="margin-top: 15%">
  <caption><form><legend> Stocks Purchased Traded or Bid For: </legend></form></caption>
  <thead>
    <tr>
    <th>Team</th>
    <th>Shares</th>
    <th>Total Points</th>
    <th>Delete Shares</th>
    </tr>
  </thead>
  <tbody>
    <% @user_shares.each do |user_share| %>
      <tr>
          <td><%="#{user_share.team.name}  |"%><%= link_to "  Bid & Ask Edit Page", edit_user_share_path(user_share) %></td>
          <td><%= user_share.number_of_shares %></td>
          <td><%= (user_share.number_of_shares * user_share.team.points_per_share).round(2) %></td>
          <td><%= link_to "Remove", user_share_path(user_share.id), method: :delete  %>         </td>
      </tr>
    <% end %>
  </tbody>
</table>