config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  get 'auth/new' => 'auth#new', as: :new_auth
  post 'auth/create' => 'auth#create', as: :create_auth
  delete 'auth/destroy' => 'auth#destroy', as: :destroy_auth
  get 'dashboard/reload_pick_teams' => 'dashboard#reload_pick_teams'
  post 'dashboard/pick_teams' => 'dashboard#pick_teams'
  post 'user_shares/create_bid' => 'user_shares#create_bid'
  post 'ask/update_js' => 'ask#update_js'

  resources :users
  resources :user_shares
  resources :ask
  resources :bid

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>B3App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class = "navbar navbar-default">
    <div>
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "Sign Out", destroy_auth_path(session: session[:team_picks]), :class=>"sign_out", method: :delete, :data => {:confirm => 'Signing Out ! Are you sure?'} %></li>
        <% else %>
          <li><%= link_to "Sign In", new_auth_path %></li>
          <li><%=link_to "Sign Up", new_user_path %></li>
          <li><%=link_to "Sign In As Guest", {:controller => "dashboard", :action => "index", :signin => "guest"} %></li>
        <% end %>
      </ul>
      <% if current_user %>
      <ul class = "nav navbar-nav navbar-right " style="margin-right: 5%">
          <li>
            <%= link_to "Initial Team Purchases", new_user_share_path %>
          </li>
      </ul>
      <ul class = "nav navbar-nav navbar-right " style="margin-right: 5%">
        <li class="dashboard">
          <%= link_to "Dashboard", root_path %>
        </li>
      </ul>
      <% end %>
    </div>
  </nav>
<div class="container">
  <div class="flash_notice">
    <%= flash[:notice] %>
  </div>
  <%= yield %>
</div>
</body class = "body">
</html>